// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_MZcJKUk5UA33nZwoRnR-5vqazUCiVXo',
    appId: '1:60143534744:web:a7f3575b7da7f3217946ed',
    messagingSenderId: '60143534744',
    projectId: 'yacht-f816d',
    authDomain: 'yacht-f816d.firebaseapp.com',
    databaseURL: 'https://yacht-f816d-default-rtdb.firebaseio.com', // CORRECT RTDB URL
    storageBucket: 'yacht-f816d.firebasestorage.app',
    measurementId: 'G-8CYTSC6VET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy7Jjjd9IwmCLUkC-_Vc4mvtxQK5v7KFc',
    appId: '1:60143534744:android:72b20a740b8a90bc7946ed',
    messagingSenderId: '60143534744',
    projectId: 'yacht-f816d',
    databaseURL: 'https://yacht-f816d-default-rtdb.firebaseio.com', // CORRECT RTDB URL
    storageBucket: 'yacht-f816d.firebasestorage.app',
  );
}
