import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart'; // Import ProviderScope
import 'package:simple_yacht/navigation/app_router.dart'; // Assuming simple_yacht is the project name
import 'package:flutter_localizations/flutter_localizations.dart'; // Import for localizations delegates
import 'package:simple_yacht/generated/app_localizations.dart'; // Import generated localizations from new path
import 'package:simple_yacht/state_management/providers/locale_provider.dart'; // Import locale provider
import 'package:simple_yacht/services/presence_service.dart'; // Import PresenceService provider
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
// import 'services/online_presence_service.dart'; // Deprecated
import 'package:firebase_auth/firebase_auth.dart';

// Ensure this file is generated by `flutterfire configure`
// If it's not present, Firebase initialization will fail.
import 'firebase_options.dart';

void main() async { // Make main async
  WidgetsFlutterBinding.ensureInitialized(); // Ensure Flutter bindings are initialized
  await Firebase.initializeApp( // Initialize Firebase
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Anonymous sign-in will be handled by the SplashScreen

  runApp(
    ProviderScope( // Wrap MyApp with ProviderScope
      child: SimpleYachtApp(),
    ),
  );
}

class SimpleYachtApp extends ConsumerStatefulWidget {
  @override
  ConsumerState<SimpleYachtApp> createState() => _SimpleYachtAppState();
}

class _SimpleYachtAppState extends ConsumerState<SimpleYachtApp> with WidgetsBindingObserver {
  // final OnlinePresenceService _presenceService = OnlinePresenceService(); // Deprecated

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    // _initializePresence(); // Deprecated: PresenceService handles its own auth state via Riverpod
    // The new PresenceService is initialized via Riverpod provider and handles auth state internally.
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    // _presenceService.goOffline(); // Deprecated: PresenceService handles its own dispose via Riverpod
    super.dispose();
  }

  // 监听应用生命周期 - This logic is now handled by the new PresenceService internally
  // or should be if app lifecycle specific online/offline calls are still needed beyond auth state.
  // For now, assuming PresenceService's auth-based logic is sufficient.
  // If explicit app lifecycle handling is needed for PresenceService, it should be added *within* PresenceService
  // or by interacting with the PresenceService provider.
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // final presenceService = ref.read(presenceServiceProvider); // Example if direct interaction needed
    // switch (state) {
    //   case AppLifecycleState.resumed:
    //     // presenceService.someMethodForResumed(); // If needed
    //     break;
    //   case AppLifecycleState.paused:
    //   case AppLifecycleState.detached:
    //     // presenceService.someMethodForPaused(); // If needed
    //     break;
    //   default:
    //     break;
    // }
  }

  // Future<void> _initializePresence() async { // Deprecated
  //   // 监听认证状态变化
  //   FirebaseAuth.instance.authStateChanges().listen((user) {
  //     if (user != null) {
  //       // _presenceService.goOnline();
  //     } else {
  //       // _presenceService.goOffline();
  //     }
  //   });
  // }

  @override
  Widget build(BuildContext context) { // Removed WidgetRef, will use this.ref
    final currentLocale = ref.watch(localeProvider);
    ref.watch(presenceServiceProvider); // Initialize PresenceService
    final router = AppRouter.createRouter(ref); // Create router instance here

    return MaterialApp.router(
      title: 'Simple Yacht',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routerConfig: router, // Use the created router instance
      locale: currentLocale, // Set the locale from the provider
      localizationsDelegates: const [
        AppLocalizations.delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en', ''), // English, no country code
        Locale('zh', ''), // Chinese, no country code
        Locale('es', ''), // Spanish
        Locale('fr', ''), // French
        Locale('de', ''), // German
        Locale('ja', ''), // Japanese
        Locale('ru', ''), // Russian
        // Add other locales your app supports
      ],
      localeResolutionCallback: (deviceLocale, supportedLocales) {
        // If user has a saved preference, use it.
        if (currentLocale != null) {
          return currentLocale;
        }
        // Otherwise, try to match device locale.
        if (deviceLocale != null) {
          for (var supportedLocale in supportedLocales) {
            if (supportedLocale.languageCode == deviceLocale.languageCode) {
              // We don't check country code here, just language.
              // If you want to be more specific, you can check deviceLocale.countryCode as well.
              return supportedLocale;
            }
          }
        }
        // If device locale is not supported or not available, fallback to English.
        return const Locale('en', '');
      },
    );
  }
}
